### ISSUE TITLE
Wrong path separator

### ISSUE THREAD

**Issue by beany-vu** [gbouthenot/grunt-css-relative-url-replace#1]
I use Windows and there are some paths which are not found(404) after running grunt.

The console log shows like this "http://sportroops.local/assets/assetsvendor%0Font-awesome%0Fonts%0Fontawesome-webfont.woff2?v=4.7.0"

I can see it's very normal from code "...assets/assetsvendor/Font-awesome/Fonts/Fontawesome-webfont.woff2?v=4.7.0"

Anyone knows about my problem? :(

**Comment by tonysamperi** [comment]
Same issue, it retrieves backslashes instead of slashes.

**Comment by gbouthenot** [comment]
Thank @tonysamperi
Should be fixed with 1bd612960b16f7054bedddbdd8d8bfbc1de3d5b3

**Comment by beany-vu** [comment]
Thanks! ^^
Let me close the task
